# tetris-deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculator-deployment
spec:
  replicas: 2 # You can adjust the number of replicas as needed
  selector:
    matchLabels:
      app: pizza-react-app
  template:
    metadata:
      labels:
        app: pizza-react-app
    spec:
      containers:
        - name: pizza-react-app
          image: yash5090/pizza-react-app # Replace with the actual image tag
          ports:
            - containerPort: 3000 # Replace with the port your Tetris game listens on
